-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_pantry
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `my_pantry` ;

-- -----------------------------------------------------
-- Schema my_pantry
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_pantry` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `my_pantry` ;

-- -----------------------------------------------------
-- Table `my_pantry`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_pantry`.`USERS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `my_pantry`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(64) NOT NULL,
  `PASSWORD` VARCHAR(32) NOT NULL,
  `EMAIL` VARCHAR(64) NOT NULL,
  `PHONE_NUMBER` VARCHAR(20) NULL DEFAULT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE ',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `USERNAME_UNIQUE` ON `my_pantry`.`USERS` (`USERNAME` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `my_pantry`.`BRANDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_pantry`.`BRANDS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `my_pantry`.`BRANDS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BRAND_NAME` VARCHAR(100) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `BRAND_NAME_UNIQUE` ON `my_pantry`.`BRANDS` (`BRAND_NAME` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `my_pantry`.`CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_pantry`.`CATEGORIES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `my_pantry`.`CATEGORIES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CATEGORY_NAME` VARCHAR(50) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `CATEGORY_NAME_UNIQUE` ON `my_pantry`.`CATEGORIES` (`CATEGORY_NAME` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `my_pantry`.`UNITS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_pantry`.`UNITS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `my_pantry`.`UNITS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UNIT_NAME` VARCHAR(50) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `UNIT_NAME_UNIQUE` ON `my_pantry`.`UNITS` (`UNIT_NAME` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `my_pantry`.`INVENTORY_ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_pantry`.`INVENTORY_ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `my_pantry`.`INVENTORY_ITEMS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BRAND_ID` INT NOT NULL,
  `CATEGORY_ID` INT NOT NULL,
  `UNIT_ID` INT NOT NULL,
  `BARCODE` VARCHAR(13) NOT NULL COMMENT '-  Use VARCHAR(13) to accommodate UPC-A (12 digits) and EAN-13 (13 digits).\n- If some items (like produce) don’t have barcodes, allow NULL.\n',
  `DESCRIPTION` VARCHAR(100) NOT NULL,
  `QUANTITY` DECIMAL(10,2) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE',
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_INVENTORY_ITEM_BRANDS1`
    FOREIGN KEY (`BRAND_ID`)
    REFERENCES `my_pantry`.`BRANDS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTORY_ITEM_CATEGORIES1`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `my_pantry`.`CATEGORIES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTORY_ITEM_UNITS1`
    FOREIGN KEY (`UNIT_ID`)
    REFERENCES `my_pantry`.`UNITS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `BARCODES_UNIQUE` ON `my_pantry`.`INVENTORY_ITEMS` (`BARCODE` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `my_pantry`.`USER_INVENTORY_ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_pantry`.`USER_INVENTORY_ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `my_pantry`.`USER_INVENTORY_ITEMS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `INVENTORY_ITEM_ID` INT NOT NULL,
  `PURCHASE_DATE` DATE NOT NULL,
  `REMAINING_QUANTITY` DECIMAL(10,2) NOT NULL,
  `USE_BY_DATE` DATE NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE',
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_STOCK_INVENTORY_ITEM1`
    FOREIGN KEY (`INVENTORY_ITEM_ID`)
    REFERENCES `my_pantry`.`INVENTORY_ITEMS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `my_pantry`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_pantry`.`ROLE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `my_pantry`.`ROLE` (
  `ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `NAME_UNIQUE` ON `my_pantry`.`ROLE` (`NAME` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `my_pantry`.`USERS_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_pantry`.`USERS_ROLES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `my_pantry`.`USERS_ROLES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE_ID` INT NOT NULL,
  `USERS_ID` INT NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE',
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_USERS_ROLES_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `my_pantry`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_ROLES_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `my_pantry`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
