-- MySQL Workbench Synchronization
-- Generated: 2025-09-15 20:12
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: wdavi

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `my_pantry`.`INVENTORY_ITEM` 
DROP FOREIGN KEY `fk_INVENTORY_ITEM_BRANDS1`,
DROP FOREIGN KEY `fk_INVENTORY_ITEM_CATEGORIES1`,
DROP FOREIGN KEY `fk_INVENTORY_ITEM_UNITS1`;

ALTER TABLE `my_pantry`.`USERS_ROLES` 
DROP FOREIGN KEY `fk_USERS_ROLES_ROLE1`,
DROP FOREIGN KEY `fk_USERS_ROLES_USERS1`;

ALTER TABLE `my_pantry`.`USERS` 
CHANGE COLUMN `PASSWORD` `PASSWORD` VARCHAR(60) NOT NULL ;

ALTER TABLE `my_pantry`.`INVENTORY_ITEM` 
DROP COLUMN `BARCODE`,
ADD COLUMN `BARCODE` VARCHAR(13) NOT NULL DEFAULT 'NO BARCODE' COMMENT '-  Use VARCHAR(13) to accommodate UPC-A (12 digits) and EAN-13 (13 digits).\n- If some items (like produce) don’t have barcodes, default to \'NO BARCODE\' because must have a value because this field is INDEXED' AFTER `UNITS_ID`,
ADD INDEX `fk_INVENTORY_ITEM_BRANDS1_idx` (`BRANDS_ID` ASC) VISIBLE,
ADD INDEX `fk_INVENTORY_ITEM_CATEGORIES1_idx` (`CATEGORIES_ID` ASC) VISIBLE,
ADD INDEX `fk_INVENTORY_ITEM_UNITS1_idx` (`UNITS_ID` ASC) INVISIBLE,
DROP INDEX `fk_INVENTORY_ITEM_UNITS1` ,
DROP INDEX `fk_INVENTORY_ITEM_CATEGORIES1` ,
DROP INDEX `fk_INVENTORY_ITEM_BRANDS1` ;
ALTER TABLE `my_pantry`.`INVENTORY_ITEM` ALTER INDEX `INVENTORY_ITEM_BARCODE_idx` VISIBLE;

CREATE TABLE IF NOT EXISTS `my_pantry`.`USERS_INVENTORY_ITEM` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USERS_ID` INT(11) NOT NULL,
  `INVENTORY_ITEM_ID` INT(11) NOT NULL,
  `PURCHASE_DATE` DATE NOT NULL,
  `REMAINING_QUANTITY` DECIMAL(10,2) NOT NULL,
  `USE_BY` DATE NOT NULL,
  `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE',
  PRIMARY KEY (`ID`),
  INDEX `fk_STOCK_INVENTORY_ITEM1_idx` (`INVENTORY_ITEM_ID` ASC) VISIBLE,
  INDEX `fk_USERS_STOCK_USERS1_idx` (`USERS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_STOCK_INVENTORY_ITEM1`
    FOREIGN KEY (`INVENTORY_ITEM_ID`)
    REFERENCES `my_pantry`.`INVENTORY_ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_STOCK_USERS1`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `my_pantry`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

ALTER TABLE `my_pantry`.`USERS_ROLES` 
ADD INDEX `fk_USERS_ROLES_ROLE1_idx` (`ROLE_ID` ASC) VISIBLE,
ADD INDEX `fk_USERS_ROLES_USERS1_idx` (`USERS_ID` ASC) VISIBLE,
DROP INDEX `fk_USERS_ROLES_USERS1` ,
DROP INDEX `fk_USERS_ROLES_ROLE1` ;
ALTER TABLE `my_pantry`.`INVENTORY_ITEM` ALTER INDEX `INVENTORY_ITEM_BARCODE_idx` VISIBLE;

ALTER TABLE `my_pantry`.`INVENTORY_ITEM` 
ADD CONSTRAINT `fk_INVENTORY_ITEM_BRANDS1`
  FOREIGN KEY (`BRANDS_ID`)
  REFERENCES `my_pantry`.`BRANDS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_INVENTORY_ITEM_CATEGORIES1`
  FOREIGN KEY (`CATEGORIES_ID`)
  REFERENCES `my_pantry`.`CATEGORIES` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_INVENTORY_ITEM_UNITS1`
  FOREIGN KEY (`UNITS_ID`)
  REFERENCES `my_pantry`.`UNITS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `my_pantry`.`USERS_ROLES` 
ADD CONSTRAINT `fk_USERS_ROLES_ROLE1`
  FOREIGN KEY (`ROLE_ID`)
  REFERENCES `my_pantry`.`ROLE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_USERS_ROLES_USERS1`
  FOREIGN KEY (`USERS_ID`)
  REFERENCES `my_pantry`.`USERS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
