-- MySQL Workbench Synchronization
-- Generated: 2025-08-19 07:21
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: wdavi
-- Added standard system audit fields: CREATED_AT, UPDATED_AT and UPDATED_BY 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER TABLE `my_pantry`.`INVENTORY_ITEM` 
DROP FOREIGN KEY `fk_INVENTORY_ITEM_BRANDS1`,
DROP FOREIGN KEY `fk_INVENTORY_ITEM_CATEGORIES1`,
DROP FOREIGN KEY `fk_INVENTORY_ITEM_UNITS1`;

ALTER TABLE `my_pantry`.`STOCK` 
DROP FOREIGN KEY `fk_STOCK_INVENTORY_ITEM1`;

ALTER TABLE `my_pantry`.`USERS_ROLES` 
DROP FOREIGN KEY `fk_USERS_ROLES_ROLE1`,
DROP FOREIGN KEY `fk_USERS_ROLES_USERS1`;

ALTER TABLE `my_pantry`.`USERS` 
ADD COLUMN `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `CREATED_AT`,
ADD COLUMN `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE ' AFTER `UPDATED_AT`,
CHANGE COLUMN `CREATE_TIME` `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ;

ALTER TABLE `my_pantry`.`BRANDS` 
ADD COLUMN `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `BRAND_NAME`,
ADD COLUMN `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `CREATED_AT`,
ADD COLUMN `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE' AFTER `UPDATED_AT`;

ALTER TABLE `my_pantry`.`CATEGORIES` 
ADD COLUMN `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `CATEGORY_NAME`,
ADD COLUMN `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `CREATED_AT`,
ADD COLUMN `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE' AFTER `UPDATED_AT`;

ALTER TABLE `my_pantry`.`INVENTORY_ITEM` 
ADD COLUMN `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `EXPIRATION_DATE`,
ADD COLUMN `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `CREATED_AT`,
ADD COLUMN `UPDATED_BY` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE' AFTER `UPDATED_AT`,
CHANGE COLUMN `BARCODES` `BARCODES` INT(11) NOT NULL COMMENT '-  Use VARCHAR(13) to accommodate UPC-A (12 digits) and EAN-13 (13 digits).\n- If some items (like produce) don’t have barcodes, allow NULL.\n' ;

ALTER TABLE `my_pantry`.`STOCK` 
ADD COLUMN `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `USE_BY`,
ADD COLUMN `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `CREATED_AT`,
ADD COLUMN `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE' AFTER `UPDATED_AT`;

ALTER TABLE `my_pantry`.`UNITS` 
ADD COLUMN `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `UNIT_NAME`,
ADD COLUMN `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `CREATED_AT`,
ADD COLUMN `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE' AFTER `UPDATED_AT`;

ALTER TABLE `my_pantry`.`ROLE` 
ADD COLUMN `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `NAME`,
ADD COLUMN `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `CREATED_AT`,
ADD COLUMN `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE' AFTER `UPDATED_AT`;

ALTER TABLE `my_pantry`.`USERS_ROLES` 
ADD COLUMN `CREATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `USERS_ID`,
ADD COLUMN `UPDATED_AT` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `CREATED_AT`,
ADD COLUMN `UPDATED_BY` VARCHAR(64) NOT NULL COMMENT 'Application will need to set this field to the USERNAME associated with the session that issued the INSERT or UPDATE' AFTER `UPDATED_AT`;

ALTER TABLE `my_pantry`.`INVENTORY_ITEM` 
ADD CONSTRAINT `fk_INVENTORY_ITEM_BRANDS1`
  FOREIGN KEY (`BRANDS_ID`)
  REFERENCES `my_pantry`.`BRANDS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_INVENTORY_ITEM_CATEGORIES1`
  FOREIGN KEY (`CATEGORIES_ID`)
  REFERENCES `my_pantry`.`CATEGORIES` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_INVENTORY_ITEM_UNITS1`
  FOREIGN KEY (`UNITS_ID`)
  REFERENCES `my_pantry`.`UNITS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `my_pantry`.`STOCK` 
ADD CONSTRAINT `fk_STOCK_INVENTORY_ITEM1`
  FOREIGN KEY (`INVENTORY_ITEM_ID`)
  REFERENCES `my_pantry`.`INVENTORY_ITEM` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `my_pantry`.`USERS_ROLES` 
ADD CONSTRAINT `fk_USERS_ROLES_ROLE1`
  FOREIGN KEY (`ROLE_ID`)
  REFERENCES `my_pantry`.`ROLE` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_USERS_ROLES_USERS1`
  FOREIGN KEY (`USERS_ID`)
  REFERENCES `my_pantry`.`USERS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
